export interface BankInfo {
  slug: string;
  name: string;
  shortName: string;
  country: 'USA' | 'UAE';
  currency: string;
  currencySymbol: string;
  locale: string;
  city: string;
  tagline: string;
  metaTitle: string;
  metaDescription: string;
  heroHeading: string;
  heroSubheading: string;
  features: string[];
  steps: { title: string; description: string }[];
  faqs: { question: string; answer: string }[];
  trustBadge: string;
}

export const banks: BankInfo[] = [
  // ─── USA Banks (15) ───
  {
    slug: 'chase',
    name: 'JPMorgan Chase Bank',
    shortName: 'Chase',
    country: 'USA',
    currency: 'USD',
    currencySymbol: '$',
    locale: 'en-US',
    city: 'New York, NY',
    tagline: 'Convert Chase PDF statements to Excel instantly',
    metaTitle: 'Chase Bank Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Free online tool to convert Chase bank statement PDFs to Excel. Extract transactions, dates, descriptions, and balances into clean XLSX format.',
    heroHeading: 'Chase Bank Statement to Excel Converter',
    heroSubheading: 'Upload your Chase PDF statement and download a clean Excel file with all transactions mapped perfectly. Works with checking, savings, and credit card statements.',
    features: [
      'Maps Chase transaction columns precisely',
      'Handles Chase checking and savings accounts',
      'Extracts balance, deposit, and withdrawal columns',
      'Supports Chase credit card statements',
    ],
    steps: [
      { title: 'Upload Chase PDF', description: 'Drag and drop your Chase bank statement PDF into the upload zone above.' },
      { title: 'Auto-detection', description: 'Our parser identifies Chase-specific column layouts including transaction dates and descriptions.' },
      { title: 'Download Excel', description: 'Get a clean XLSX file with every Chase transaction row mapped accurately.' },
    ],
    faqs: [
      { question: 'Does this work with Chase credit card statements?', answer: 'Yes, the converter handles both Chase checking account statements and Chase credit card PDF statements.' },
      { question: 'Are my Chase account details stored?', answer: 'No. Files are processed on the fly and never stored on our servers after conversion.' },
    ],
    trustBadge: 'Optimized for Chase PDF layouts',
  },
  {
    slug: 'bank-of-america',
    name: 'Bank of America Corporation',
    shortName: 'Bank of America',
    country: 'USA',
    currency: 'USD',
    currencySymbol: '$',
    locale: 'en-US',
    city: 'Charlotte, NC',
    tagline: 'Convert Bank of America PDF statements to Excel',
    metaTitle: 'Bank of America Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert Bank of America bank statement PDFs to Excel online. Extract transactions with dates, descriptions, and amounts into clean XLSX format.',
    heroHeading: 'Bank of America Statement to Excel Converter',
    heroSubheading: 'Transform your Bank of America PDF statements into structured Excel files. Every transaction row is extracted with column precision for BofA formats.',
    features: [
      'Recognizes Bank of America statement layouts',
      'Extracts posted and pending transactions',
      'Maps BofA amount and balance columns',
      'Works with BofA checking and credit card PDFs',
    ],
    steps: [
      { title: 'Upload BofA PDF', description: 'Select or drop your Bank of America statement PDF into the upload area.' },
      { title: 'Smart parsing', description: 'The parser detects Bank of America column structures including reference numbers and balances.' },
      { title: 'Get your Excel', description: 'Download a formatted XLSX with all Bank of America transactions accurately mapped.' },
    ],
    faqs: [
      { question: 'Can I convert multiple Bank of America statements at once?', answer: 'Yes, you can upload up to 2 Bank of America PDF statements simultaneously for conversion.' },
      { question: 'Is the converter free for Bank of America statements?', answer: 'Yes, you get 2 free conversions per month. Upgrade to Pro for unlimited conversions.' },
    ],
    trustBadge: 'Built for Bank of America formats',
  },
  {
    slug: 'wells-fargo',
    name: 'Wells Fargo & Company',
    shortName: 'Wells Fargo',
    country: 'USA',
    currency: 'USD',
    currencySymbol: '$',
    locale: 'en-US',
    city: 'San Francisco, CA',
    tagline: 'Convert Wells Fargo PDF statements to Excel',
    metaTitle: 'Wells Fargo Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Free tool to convert Wells Fargo bank statement PDFs to Excel. Extract transactions, amounts, and balances into a clean spreadsheet.',
    heroHeading: 'Wells Fargo Statement to Excel Converter',
    heroSubheading: 'Upload your Wells Fargo PDF statement and get a perfectly structured Excel file. Handles all Wells Fargo account types with precision column mapping.',
    features: [
      'Parses Wells Fargo daily balance summaries',
      'Extracts Wells Fargo deposit and withdrawal columns',
      'Handles Wells Fargo business account statements',
      'Maps Wells Fargo transaction descriptions accurately',
    ],
    steps: [
      { title: 'Upload Wells Fargo PDF', description: 'Drop your Wells Fargo statement PDF into the upload zone.' },
      { title: 'Column detection', description: 'Our system identifies Wells Fargo specific columns like running balance and check numbers.' },
      { title: 'Export to Excel', description: 'Receive a clean Excel file with every Wells Fargo transaction row properly aligned.' },
    ],
    faqs: [
      { question: 'Does it work with Wells Fargo business account statements?', answer: 'Yes, the converter handles both personal and business Wells Fargo account statements.' },
      { question: 'How accurate is the Wells Fargo transaction extraction?', answer: 'Our parser maps each column from your Wells Fargo statement with 0% cell shifting, preserving the original structure.' },
    ],
    trustBadge: 'Optimized for Wells Fargo PDFs',
  },
  {
    slug: 'citi',
    name: 'Citibank, N.A.',
    shortName: 'Citi',
    country: 'USA',
    currency: 'USD',
    currencySymbol: '$',
    locale: 'en-US',
    city: 'New York, NY',
    tagline: 'Convert Citi PDF statements to Excel',
    metaTitle: 'Citi Bank Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert Citibank statement PDFs to Excel online. Extract Citi transactions with dates, descriptions, and amounts into clean XLSX format.',
    heroHeading: 'Citi Statement to Excel Converter',
    heroSubheading: 'Convert your Citibank PDF statements into organized Excel files. Our parser handles Citi-specific formats including credit card and banking statements.',
    features: [
      'Handles Citi credit card statement formats',
      'Maps Citi transaction and posted-date columns',
      'Extracts Citi rewards and payment columns',
      'Supports Citi checking and savings statements',
    ],
    steps: [
      { title: 'Upload Citi PDF', description: 'Add your Citibank statement PDF to the upload zone.' },
      { title: 'Format detection', description: 'The parser recognizes Citi statement layouts and maps each column correctly.' },
      { title: 'Download Excel file', description: 'Get an XLSX file with all Citi transactions in clean tabular format.' },
    ],
    faqs: [
      { question: 'Can I convert Citi credit card statements?', answer: 'Yes, Citi credit card PDF statements are fully supported with accurate column mapping.' },
      { question: 'What Citi statement formats are supported?', answer: 'We support all standard Citibank PDF statement formats including checking, savings, and credit card statements.' },
    ],
    trustBadge: 'Tailored for Citi statement layouts',
  },
  {
    slug: 'us-bank',
    name: 'U.S. Bancorp',
    shortName: 'US Bank',
    country: 'USA',
    currency: 'USD',
    currencySymbol: '$',
    locale: 'en-US',
    city: 'Minneapolis, MN',
    tagline: 'Convert US Bank PDF statements to Excel',
    metaTitle: 'US Bank Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert US Bank statement PDFs to Excel online. Extract transactions, deposits, withdrawals, and balances into a clean XLSX spreadsheet.',
    heroHeading: 'US Bank Statement to Excel Converter',
    heroSubheading: 'Transform your US Bank PDF statements into clean Excel files. Every transaction is extracted with precise column alignment for US Bank formats.',
    features: [
      'Parses US Bank checking and savings statements',
      'Extracts US Bank withdrawal and deposit columns',
      'Maps US Bank running balance fields',
      'Handles US Bank credit card statements',
    ],
    steps: [
      { title: 'Upload US Bank PDF', description: 'Drag your US Bank statement PDF into the upload zone.' },
      { title: 'Structure detection', description: 'Our parser identifies US Bank column layouts and transaction patterns.' },
      { title: 'Export Excel', description: 'Download a formatted Excel file with every US Bank transaction mapped.' },
    ],
    faqs: [
      { question: 'Does it support US Bank business account statements?', answer: 'Yes, US Bank business and personal account PDFs are both supported.' },
      { question: 'How long does conversion take?', answer: 'Most US Bank statement conversions complete in under 30 seconds.' },
    ],
    trustBadge: 'Built for US Bank PDF formats',
  },
  {
    slug: 'pnc',
    name: 'PNC Financial Services Group',
    shortName: 'PNC Bank',
    country: 'USA',
    currency: 'USD',
    currencySymbol: '$',
    locale: 'en-US',
    city: 'Pittsburgh, PA',
    tagline: 'Convert PNC Bank PDF statements to Excel',
    metaTitle: 'PNC Bank Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert PNC Bank statement PDFs to Excel. Extract PNC transactions with dates, descriptions, and amounts into a clean spreadsheet.',
    heroHeading: 'PNC Bank Statement to Excel Converter',
    heroSubheading: 'Upload your PNC Bank PDF statement and receive a clean Excel file. Our parser handles PNC-specific column layouts with full accuracy.',
    features: [
      'Recognizes PNC Bank Virtual Wallet statements',
      'Extracts PNC transaction and balance columns',
      'Maps PNC debit and credit columns',
      'Supports PNC checking and savings PDFs',
    ],
    steps: [
      { title: 'Upload PNC PDF', description: 'Drop your PNC Bank statement PDF into the upload area.' },
      { title: 'Column mapping', description: 'The parser detects PNC Bank column structures and maps each field.' },
      { title: 'Get Excel file', description: 'Download a clean XLSX with all PNC Bank transactions aligned.' },
    ],
    faqs: [
      { question: 'Does it work with PNC Virtual Wallet statements?', answer: 'Yes, PNC Virtual Wallet PDF statements are fully supported.' },
      { question: 'Can I convert PNC credit card statements?', answer: 'Yes, PNC credit card PDF statements work with the converter.' },
    ],
    trustBadge: 'Optimized for PNC Bank layouts',
  },
  {
    slug: 'capital-one',
    name: 'Capital One Financial Corporation',
    shortName: 'Capital One',
    country: 'USA',
    currency: 'USD',
    currencySymbol: '$',
    locale: 'en-US',
    city: 'McLean, VA',
    tagline: 'Convert Capital One PDF statements to Excel',
    metaTitle: 'Capital One Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert Capital One statement PDFs to Excel online. Extract transactions, payments, and balances from Capital One credit card and banking statements.',
    heroHeading: 'Capital One Statement to Excel Converter',
    heroSubheading: 'Convert your Capital One PDF statements into structured Excel files. Perfect for Capital One 360 checking and credit card statement formats.',
    features: [
      'Handles Capital One 360 checking statements',
      'Maps Capital One credit card transaction columns',
      'Extracts Capital One payment and purchase columns',
      'Supports Capital One auto finance statements',
    ],
    steps: [
      { title: 'Upload Capital One PDF', description: 'Add your Capital One statement PDF to the upload zone.' },
      { title: 'Format recognition', description: 'The parser identifies Capital One statement layouts automatically.' },
      { title: 'Download Excel', description: 'Get a clean XLSX with all Capital One transactions extracted.' },
    ],
    faqs: [
      { question: 'Does it work with Capital One 360 statements?', answer: 'Yes, Capital One 360 checking and savings PDF statements are supported.' },
      { question: 'Can I convert Capital One credit card statements?', answer: 'Absolutely, Capital One credit card PDF statements are fully compatible.' },
    ],
    trustBadge: 'Tailored for Capital One formats',
  },
  {
    slug: 'truist',
    name: 'Truist Financial Corporation',
    shortName: 'Truist',
    country: 'USA',
    currency: 'USD',
    currencySymbol: '$',
    locale: 'en-US',
    city: 'Charlotte, NC',
    tagline: 'Convert Truist PDF statements to Excel',
    metaTitle: 'Truist Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert Truist bank statement PDFs to Excel online. Extract transactions, deposits, and withdrawals from Truist statements into clean XLSX format.',
    heroHeading: 'Truist Statement to Excel Converter',
    heroSubheading: 'Upload your Truist PDF statement and get a perfectly formatted Excel file. Handles both legacy BB&T and SunTrust statement formats.',
    features: [
      'Parses Truist (BB&T / SunTrust) statement formats',
      'Extracts Truist deposit and withdrawal columns',
      'Maps Truist running balance fields',
      'Supports Truist checking and credit card PDFs',
    ],
    steps: [
      { title: 'Upload Truist PDF', description: 'Drop your Truist statement PDF into the upload zone.' },
      { title: 'Format detection', description: 'The parser handles Truist and legacy BB&T/SunTrust layouts.' },
      { title: 'Export to Excel', description: 'Download a clean Excel file with all Truist transactions mapped.' },
    ],
    faqs: [
      { question: 'Does it support legacy BB&T or SunTrust statements?', answer: 'Yes, the converter handles both Truist branded and legacy BB&T/SunTrust PDF statements.' },
      { question: 'Is it free to convert Truist statements?', answer: 'You get 2 free conversions per month. Upgrade to Pro for unlimited Truist statement conversions.' },
    ],
    trustBadge: 'Built for Truist PDF layouts',
  },
  {
    slug: 'goldman-sachs-marcus',
    name: 'Goldman Sachs Bank USA (Marcus)',
    shortName: 'Marcus',
    country: 'USA',
    currency: 'USD',
    currencySymbol: '$',
    locale: 'en-US',
    city: 'New York, NY',
    tagline: 'Convert Marcus by Goldman Sachs PDF statements to Excel',
    metaTitle: 'Marcus Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert Marcus by Goldman Sachs statement PDFs to Excel. Extract savings transactions, interest, and balances into clean XLSX format.',
    heroHeading: 'Marcus Statement to Excel Converter',
    heroSubheading: 'Convert your Marcus by Goldman Sachs PDF statements into clean Excel files. Extracts interest, deposits, and balance columns with precision.',
    features: [
      'Handles Marcus savings account statements',
      'Extracts Marcus interest and deposit columns',
      'Maps Marcus running balance fields',
      'Supports Marcus personal loan statements',
    ],
    steps: [
      { title: 'Upload Marcus PDF', description: 'Drag your Marcus statement PDF into the upload zone.' },
      { title: 'Column detection', description: 'The parser identifies Marcus-specific columns like interest earned and deposits.' },
      { title: 'Download Excel', description: 'Get a formatted XLSX with all Marcus transactions aligned.' },
    ],
    faqs: [
      { question: 'Does it work with Marcus personal loan statements?', answer: 'Yes, Marcus personal loan PDF statements are supported alongside savings statements.' },
      { question: 'Can I extract interest earned from Marcus statements?', answer: 'Yes, the parser maps interest columns from Marcus savings statements accurately.' },
    ],
    trustBadge: 'Optimized for Marcus PDF formats',
  },
  {
    slug: 'ally',
    name: 'Ally Financial Inc.',
    shortName: 'Ally',
    country: 'USA',
    currency: 'USD',
    currencySymbol: '$',
    locale: 'en-US',
    city: 'Detroit, MI',
    tagline: 'Convert Ally Bank PDF statements to Excel',
    metaTitle: 'Ally Bank Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert Ally Bank statement PDFs to Excel. Extract transactions, interest, and balances from Ally checking and savings statements.',
    heroHeading: 'Ally Bank Statement to Excel Converter',
    heroSubheading: 'Upload your Ally Bank PDF statement and receive a clean Excel file. Our parser handles Ally-specific formats including interest and transfer columns.',
    features: [
      'Parses Ally Bank online savings statements',
      'Extracts Ally interest and transfer columns',
      'Maps Ally checking and deposit columns',
      'Handles Ally auto loan statements',
    ],
    steps: [
      { title: 'Upload Ally PDF', description: 'Drop your Ally Bank statement PDF into the upload area.' },
      { title: 'Smart detection', description: 'The parser identifies Ally Bank column layouts including interest and transfers.' },
      { title: 'Export Excel', description: 'Download a clean XLSX with all Ally Bank transactions mapped.' },
    ],
    faqs: [
      { question: 'Does it support Ally auto loan statements?', answer: 'Yes, Ally auto loan PDF statements are supported alongside banking statements.' },
      { question: 'Can I convert Ally interest-bearing account statements?', answer: 'Yes, interest columns from Ally savings and money market accounts are extracted accurately.' },
    ],
    trustBadge: 'Built for Ally Bank formats',
  },
  {
    slug: 'synchrony',
    name: 'Synchrony Financial',
    shortName: 'Synchrony',
    country: 'USA',
    currency: 'USD',
    currencySymbol: '$',
    locale: 'en-US',
    city: 'Stamford, CT',
    tagline: 'Convert Synchrony Bank PDF statements to Excel',
    metaTitle: 'Synchrony Bank Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert Synchrony Bank statement PDFs to Excel online. Extract savings, interest, and transaction data into clean XLSX format.',
    heroHeading: 'Synchrony Bank Statement to Excel Converter',
    heroSubheading: 'Transform your Synchrony Bank PDF statements into organized Excel files. Handles Synchrony savings and credit card statement formats.',
    features: [
      'Handles Synchrony high-yield savings statements',
      'Extracts Synchrony interest and deposit columns',
      'Maps Synchrony credit card transaction columns',
      'Supports Synchrony CD account statements',
    ],
    steps: [
      { title: 'Upload Synchrony PDF', description: 'Add your Synchrony Bank statement PDF to the upload zone.' },
      { title: 'Format detection', description: 'The parser recognizes Synchrony Bank statement layouts automatically.' },
      { title: 'Download Excel', description: 'Get a clean XLSX with all Synchrony transactions extracted.' },
    ],
    faqs: [
      { question: 'Does it work with Synchrony credit card statements?', answer: 'Yes, Synchrony credit card PDF statements are supported including store card statements.' },
      { question: 'Can I extract interest from Synchrony savings statements?', answer: 'Yes, interest earned columns from Synchrony savings accounts are mapped accurately.' },
    ],
    trustBadge: 'Tailored for Synchrony Bank PDFs',
  },
  {
    slug: 'discover',
    name: 'Discover Financial Services',
    shortName: 'Discover',
    country: 'USA',
    currency: 'USD',
    currencySymbol: '$',
    locale: 'en-US',
    city: 'Riverwoods, IL',
    tagline: 'Convert Discover PDF statements to Excel',
    metaTitle: 'Discover Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert Discover bank and credit card statement PDFs to Excel. Extract transactions, payments, rewards, and balances into clean XLSX format.',
    heroHeading: 'Discover Statement to Excel Converter',
    heroSubheading: 'Upload your Discover PDF statement and get a clean Excel file. Handles Discover credit card, checking, and savings statement formats.',
    features: [
      'Parses Discover credit card statement formats',
      'Extracts Discover cashback and rewards columns',
      'Maps Discover payment and purchase columns',
      'Supports Discover checking and savings PDFs',
    ],
    steps: [
      { title: 'Upload Discover PDF', description: 'Drop your Discover statement PDF into the upload zone.' },
      { title: 'Column detection', description: 'The parser identifies Discover-specific columns including rewards and cashback.' },
      { title: 'Export Excel', description: 'Download a clean XLSX with all Discover transactions mapped.' },
    ],
    faqs: [
      { question: 'Can I extract Discover cashback rewards?', answer: 'Yes, Discover cashback and rewards columns are mapped from credit card statements.' },
      { question: 'Does it work with Discover checking statements?', answer: 'Yes, Discover checking and savings PDF statements are fully supported.' },
    ],
    trustBadge: 'Optimized for Discover formats',
  },
  {
    slug: 'regions',
    name: 'Regions Financial Corporation',
    shortName: 'Regions',
    country: 'USA',
    currency: 'USD',
    currencySymbol: '$',
    locale: 'en-US',
    city: 'Birmingham, AL',
    tagline: 'Convert Regions Bank PDF statements to Excel',
    metaTitle: 'Regions Bank Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert Regions Bank statement PDFs to Excel online. Extract transactions, deposits, withdrawals, and balances into clean XLSX format.',
    heroHeading: 'Regions Bank Statement to Excel Converter',
    heroSubheading: 'Convert your Regions Bank PDF statements into structured Excel files. Every transaction row is extracted with column precision for Regions formats.',
    features: [
      'Recognizes Regions Bank statement layouts',
      'Extracts Regions deposit and withdrawal columns',
      'Maps Regions running balance fields',
      'Supports Regions checking and savings PDFs',
    ],
    steps: [
      { title: 'Upload Regions PDF', description: 'Select or drop your Regions Bank statement PDF.' },
      { title: 'Smart parsing', description: 'The parser detects Regions Bank column structures and transaction patterns.' },
      { title: 'Get your Excel', description: 'Download a formatted XLSX with all Regions Bank transactions aligned.' },
    ],
    faqs: [
      { question: 'Does it support Regions business account statements?', answer: 'Yes, Regions Bank business and personal account PDFs are both supported.' },
      { question: 'How accurate is the Regions transaction extraction?', answer: 'Each column from your Regions statement is mapped with 0% cell shifting, preserving the original structure.' },
    ],
    trustBadge: 'Built for Regions Bank PDFs',
  },
  {
    slug: 'fifth-third',
    name: 'Fifth Third Bancorp',
    shortName: 'Fifth Third',
    country: 'USA',
    currency: 'USD',
    currencySymbol: '$',
    locale: 'en-US',
    city: 'Cincinnati, OH',
    tagline: 'Convert Fifth Third Bank PDF statements to Excel',
    metaTitle: 'Fifth Third Bank Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert Fifth Third Bank statement PDFs to Excel. Extract transactions, amounts, and balances into a clean XLSX spreadsheet.',
    heroHeading: 'Fifth Third Bank Statement to Excel Converter',
    heroSubheading: 'Upload your Fifth Third Bank PDF statement and receive a perfectly formatted Excel file with all transactions mapped accurately.',
    features: [
      'Parses Fifth Third checking and savings statements',
      'Extracts Fifth Third debit and credit columns',
      'Maps Fifth Third running balance fields',
      'Handles Fifth Third credit card PDFs',
    ],
    steps: [
      { title: 'Upload Fifth Third PDF', description: 'Drop your Fifth Third Bank statement PDF into the upload zone.' },
      { title: 'Structure detection', description: 'The parser identifies Fifth Third column layouts automatically.' },
      { title: 'Export Excel', description: 'Download a clean Excel file with every Fifth Third transaction mapped.' },
    ],
    faqs: [
      { question: 'Does it work with Fifth Third credit card statements?', answer: 'Yes, Fifth Third credit card PDF statements are fully supported.' },
      { question: 'Can I convert Fifth Third business account statements?', answer: 'Yes, both personal and business Fifth Third account PDFs work with the converter.' },
    ],
    trustBadge: 'Optimized for Fifth Third formats',
  },
  {
    slug: 'keybank',
    name: 'KeyCorp (KeyBank)',
    shortName: 'KeyBank',
    country: 'USA',
    currency: 'USD',
    currencySymbol: '$',
    locale: 'en-US',
    city: 'Cleveland, OH',
    tagline: 'Convert KeyBank PDF statements to Excel',
    metaTitle: 'KeyBank Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert KeyBank statement PDFs to Excel online. Extract transactions, deposits, and balances into clean XLSX spreadsheet format.',
    heroHeading: 'KeyBank Statement to Excel Converter',
    heroSubheading: 'Transform your KeyBank PDF statements into organized Excel files. Handles KeyBank checking, savings, and credit card statement formats.',
    features: [
      'Handles KeyBank checking and savings statements',
      'Extracts KeyBank withdrawal and deposit columns',
      'Maps KeyBank running balance fields',
      'Supports KeyBank credit card PDFs',
    ],
    steps: [
      { title: 'Upload KeyBank PDF', description: 'Add your KeyBank statement PDF to the upload zone.' },
      { title: 'Format detection', description: 'The parser recognizes KeyBank statement layouts automatically.' },
      { title: 'Download Excel', description: 'Get a clean XLSX with all KeyBank transactions extracted.' },
    ],
    faqs: [
      { question: 'Does it work with KeyBank business statements?', answer: 'Yes, KeyBank business and personal account PDFs are both supported.' },
      { question: 'What KeyBank statement types are supported?', answer: 'Checking, savings, money market, and credit card KeyBank PDF statements all work.' },
    ],
    trustBadge: 'Tailored for KeyBank PDF layouts',
  },

  // ─── UAE Banks (15) ───
  {
    slug: 'emirates-nbd',
    name: 'Emirates NBD Bank PJSC',
    shortName: 'Emirates NBD',
    country: 'UAE',
    currency: 'AED',
    currencySymbol: 'AED',
    locale: 'en-AE',
    city: 'Dubai',
    tagline: 'Convert Emirates NBD PDF statements to Excel',
    metaTitle: 'Emirates NBD Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert Emirates NBD bank statement PDFs to Excel online. Extract AED transactions, dates, descriptions, and balances into clean XLSX format.',
    heroHeading: 'Emirates NBD Statement to Excel Converter',
    heroSubheading: 'Upload your Emirates NBD PDF statement and download a clean Excel file with all AED transactions mapped perfectly. Works with current and savings accounts.',
    features: [
      'Maps Emirates NBD transaction columns precisely',
      'Handles Emirates NBD current and savings accounts',
      'Extracts AED debit, credit, and balance columns',
      'Supports Emirates NBD credit card statements',
    ],
    steps: [
      { title: 'Upload Emirates NBD PDF', description: 'Drag and drop your Emirates NBD statement PDF into the upload zone.' },
      { title: 'Auto-detection', description: 'Our parser identifies Emirates NBD column layouts including transaction dates and AED amounts.' },
      { title: 'Download Excel', description: 'Get a clean XLSX file with every Emirates NBD transaction row mapped accurately.' },
    ],
    faqs: [
      { question: 'Does this work with Emirates NBD credit card statements?', answer: 'Yes, the converter handles Emirates NBD credit card PDF statements alongside current and savings accounts.' },
      { question: 'Are AED amounts preserved correctly?', answer: 'Yes, all AED transaction amounts and balances are extracted with full decimal precision.' },
    ],
    trustBadge: 'Optimized for Emirates NBD PDF layouts',
  },
  {
    slug: 'adcb',
    name: 'Abu Dhabi Commercial Bank',
    shortName: 'ADCB',
    country: 'UAE',
    currency: 'AED',
    currencySymbol: 'AED',
    locale: 'en-AE',
    city: 'Abu Dhabi',
    tagline: 'Convert ADCB PDF statements to Excel',
    metaTitle: 'ADCB Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert ADCB bank statement PDFs to Excel online. Extract AED transactions, dates, descriptions, and balances into clean XLSX format.',
    heroHeading: 'ADCB Statement to Excel Converter',
    heroSubheading: 'Transform your ADCB PDF statements into structured Excel files. Every AED transaction row is extracted with column precision for ADCB formats.',
    features: [
      'Recognizes ADCB statement layouts',
      'Extracts ADCB AED debit and credit columns',
      'Maps ADCB running balance fields',
      'Supports ADCB current and savings PDFs',
    ],
    steps: [
      { title: 'Upload ADCB PDF', description: 'Select or drop your ADCB statement PDF into the upload area.' },
      { title: 'Smart parsing', description: 'The parser detects ADCB column structures including reference numbers and AED balances.' },
      { title: 'Get your Excel', description: 'Download a formatted XLSX with all ADCB transactions accurately mapped.' },
    ],
    faqs: [
      { question: 'Can I convert multiple ADCB statements at once?', answer: 'Yes, you can upload up to 2 ADCB PDF statements simultaneously for conversion.' },
      { question: 'Are ADCB AED amounts extracted correctly?', answer: 'Yes, all AED transaction amounts are preserved with full decimal precision in the Excel output.' },
    ],
    trustBadge: 'Built for ADCB PDF formats',
  },
  {
    slug: 'fab',
    name: 'First Abu Dhabi Bank (FAB)',
    shortName: 'FAB',
    country: 'UAE',
    currency: 'AED',
    currencySymbol: 'AED',
    locale: 'en-AE',
    city: 'Abu Dhabi',
    tagline: 'Convert FAB PDF statements to Excel',
    metaTitle: 'FAB Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert First Abu Dhabi Bank statement PDFs to Excel. Extract AED transactions, deposits, and balances into a clean spreadsheet.',
    heroHeading: 'First Abu Dhabi Bank Statement to Excel Converter',
    heroSubheading: 'Upload your FAB PDF statement and get a perfectly structured Excel file. Handles all FAB account types with precision column mapping.',
    features: [
      'Parses FAB current account statements',
      'Extracts FAB AED deposit and withdrawal columns',
      'Handles FAB prestige and elite account statements',
      'Maps FAB transaction descriptions accurately',
    ],
    steps: [
      { title: 'Upload FAB PDF', description: 'Drop your First Abu Dhabi Bank statement PDF into the upload zone.' },
      { title: 'Column detection', description: 'Our system identifies FAB-specific columns like running balance and cheque numbers.' },
      { title: 'Export to Excel', description: 'Receive a clean Excel file with every FAB transaction row properly aligned.' },
    ],
    faqs: [
      { question: 'Does it work with FAB prestige account statements?', answer: 'Yes, FAB prestige, elite, and standard current account PDF statements are all supported.' },
      { question: 'How accurate is the FAB transaction extraction?', answer: 'Each column from your FAB statement is mapped with 0% cell shifting, preserving the original structure.' },
    ],
    trustBadge: 'Optimized for FAB PDF layouts',
  },
  {
    slug: 'dubai-islamic',
    name: 'Dubai Islamic Bank (DIB)',
    shortName: 'Dubai Islamic',
    country: 'UAE',
    currency: 'AED',
    currencySymbol: 'AED',
    locale: 'en-AE',
    city: 'Dubai',
    tagline: 'Convert Dubai Islamic Bank PDF statements to Excel',
    metaTitle: 'Dubai Islamic Bank Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert Dubai Islamic Bank statement PDFs to Excel. Extract AED transactions, dates, and balances from DIB statements into clean XLSX format.',
    heroHeading: 'Dubai Islamic Bank Statement to Excel Converter',
    heroSubheading: 'Convert your DIB PDF statements into organized Excel files. Our parser handles Dubai Islamic Bank-specific formats including Sharia-compliant accounts.',
    features: [
      'Handles Dubai Islamic Bank current account statements',
      'Maps DIB AED transaction and balance columns',
      'Extracts DIB debit and credit columns',
      'Supports DIB savings and credit card PDFs',
    ],
    steps: [
      { title: 'Upload DIB PDF', description: 'Add your Dubai Islamic Bank statement PDF to the upload zone.' },
      { title: 'Format detection', description: 'The parser recognizes DIB statement layouts and maps each column correctly.' },
      { title: 'Download Excel file', description: 'Get an XLSX file with all DIB transactions in clean tabular format.' },
    ],
    faqs: [
      { question: 'Can I convert DIB Sharia-compliant account statements?', answer: 'Yes, Dubai Islamic Bank Sharia-compliant account PDF statements are fully supported.' },
      { question: 'What DIB statement formats are supported?', answer: 'We support DIB current, savings, and credit card PDF statement formats.' },
    ],
    trustBadge: 'Tailored for DIB statement layouts',
  },
  {
    slug: 'mashreq',
    name: 'Mashreq Bank PSBC',
    shortName: 'Mashreq',
    country: 'UAE',
    currency: 'AED',
    currencySymbol: 'AED',
    locale: 'en-AE',
    city: 'Dubai',
    tagline: 'Convert Mashreq Bank PDF statements to Excel',
    metaTitle: 'Mashreq Bank Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert Mashreq Bank statement PDFs to Excel online. Extract AED transactions, deposits, withdrawals, and balances into clean XLSX format.',
    heroHeading: 'Mashreq Bank Statement to Excel Converter',
    heroSubheading: 'Transform your Mashreq Bank PDF statements into clean Excel files. Every AED transaction is extracted with precise column alignment.',
    features: [
      'Parses Mashreq current and savings statements',
      'Extracts Mashreq AED withdrawal and deposit columns',
      'Maps Mashreq running balance fields',
      'Handles Mashreq Neo account statements',
    ],
    steps: [
      { title: 'Upload Mashreq PDF', description: 'Drag your Mashreq Bank statement PDF into the upload zone.' },
      { title: 'Structure detection', description: 'The parser identifies Mashreq column layouts and transaction patterns.' },
      { title: 'Export Excel', description: 'Download a formatted Excel file with every Mashreq transaction mapped.' },
    ],
    faqs: [
      { question: 'Does it support Mashreq Neo account statements?', answer: 'Yes, Mashreq Neo digital account PDF statements are fully supported.' },
      { question: 'Are Mashreq multi-currency statements supported?', answer: 'The converter handles AED transactions. Multi-currency statements may require separate conversion per currency.' },
    ],
    trustBadge: 'Built for Mashreq PDF formats',
  },
  {
    slug: 'rakbank',
    name: 'RakBank (RAKBANK)',
    shortName: 'RakBank',
    country: 'UAE',
    currency: 'AED',
    currencySymbol: 'AED',
    locale: 'en-AE',
    city: 'Ras Al Khaimah',
    tagline: 'Convert RakBank PDF statements to Excel',
    metaTitle: 'RakBank Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert RakBank statement PDFs to Excel. Extract AED transactions, amounts, and balances from RakBank statements into clean XLSX format.',
    heroHeading: 'RakBank Statement to Excel Converter',
    heroSubheading: 'Upload your RakBank PDF statement and receive a clean Excel file. Our parser handles RakBank-specific column layouts with full accuracy.',
    features: [
      'Recognizes RakBank current account statements',
      'Extracts RakBank AED debit and credit columns',
      'Maps RakBank running balance fields',
      'Supports RakBank credit card PDFs',
    ],
    steps: [
      { title: 'Upload RakBank PDF', description: 'Drop your RakBank statement PDF into the upload area.' },
      { title: 'Column mapping', description: 'The parser detects RakBank column structures and maps each field.' },
      { title: 'Get Excel file', description: 'Download a clean XLSX with all RakBank transactions aligned.' },
    ],
    faqs: [
      { question: 'Does it work with RakBank credit card statements?', answer: 'Yes, RakBank credit card PDF statements are fully supported.' },
      { question: 'Can I convert RakBank RAKstars account statements?', answer: 'Yes, RakBank premium and standard account PDFs both work with the converter.' },
    ],
    trustBadge: 'Optimized for RakBank layouts',
  },
  {
    slug: 'standard-chartered-uae',
    name: 'Standard Chartered Bank (UAE)',
    shortName: 'Standard Chartered UAE',
    country: 'UAE',
    currency: 'AED',
    currencySymbol: 'AED',
    locale: 'en-AE',
    city: 'Dubai',
    tagline: 'Convert Standard Chartered UAE PDF statements to Excel',
    metaTitle: 'Standard Chartered UAE Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert Standard Chartered Bank UAE statement PDFs to Excel. Extract AED transactions, payments, and balances into clean XLSX format.',
    heroHeading: 'Standard Chartered UAE Statement to Excel Converter',
    heroSubheading: 'Convert your Standard Chartered UAE PDF statements into structured Excel files. Handles SCB UAE current, savings, and credit card formats.',
    features: [
      'Handles Standard Chartered UAE current account statements',
      'Maps SCB UAE credit card transaction columns',
      'Extracts SCB UAE AED payment and purchase columns',
      'Supports SCB UAE savings account PDFs',
    ],
    steps: [
      { title: 'Upload SCB UAE PDF', description: 'Add your Standard Chartered UAE statement PDF to the upload zone.' },
      { title: 'Format recognition', description: 'The parser identifies Standard Chartered UAE statement layouts automatically.' },
      { title: 'Download Excel', description: 'Get a clean XLSX with all SCB UAE transactions extracted.' },
    ],
    faqs: [
      { question: 'Does it work with Standard Chartered UAE credit cards?', answer: 'Yes, Standard Chartered UAE credit card PDF statements are fully compatible.' },
      { question: 'Can I convert SCB UAE Priority Banking statements?', answer: 'Yes, Standard Chartered Priority Banking account PDFs are supported.' },
    ],
    trustBadge: 'Tailored for SCB UAE formats',
  },
  {
    slug: 'hsbc-uae',
    name: 'HSBC Bank Middle East (UAE)',
    shortName: 'HSBC UAE',
    country: 'UAE',
    currency: 'AED',
    currencySymbol: 'AED',
    locale: 'en-AE',
    city: 'Dubai',
    tagline: 'Convert HSBC UAE PDF statements to Excel',
    metaTitle: 'HSBC UAE Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert HSBC UAE statement PDFs to Excel online. Extract AED transactions, deposits, and withdrawals into clean XLSX format.',
    heroHeading: 'HSBC UAE Statement to Excel Converter',
    heroSubheading: 'Upload your HSBC UAE PDF statement and get a perfectly formatted Excel file. Handles HSBC Premier, Advance, and standard account formats.',
    features: [
      'Parses HSBC UAE Premier account statements',
      'Extracts HSBC UAE AED deposit and withdrawal columns',
      'Maps HSBC UAE running balance fields',
      'Supports HSBC UAE credit card PDFs',
    ],
    steps: [
      { title: 'Upload HSBC UAE PDF', description: 'Drop your HSBC UAE statement PDF into the upload zone.' },
      { title: 'Format detection', description: 'The parser handles HSBC UAE Premier, Advance, and standard layouts.' },
      { title: 'Export to Excel', description: 'Download a clean Excel file with all HSBC UAE transactions mapped.' },
    ],
    faqs: [
      { question: 'Does it support HSBC Premier UAE statements?', answer: 'Yes, HSBC Premier, Advance, and standard UAE account PDF statements are all supported.' },
      { question: 'Is it free to convert HSBC UAE statements?', answer: 'You get 2 free conversions per month. Upgrade to Pro for unlimited HSBC UAE conversions.' },
    ],
    trustBadge: 'Built for HSBC UAE PDF layouts',
  },
  {
    slug: 'cbd',
    name: 'Commercial Bank of Dubai (CBD)',
    shortName: 'CBD',
    country: 'UAE',
    currency: 'AED',
    currencySymbol: 'AED',
    locale: 'en-AE',
    city: 'Dubai',
    tagline: 'Convert CBD PDF statements to Excel',
    metaTitle: 'Commercial Bank of Dubai Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert Commercial Bank of Dubai statement PDFs to Excel. Extract AED transactions, interest, and balances into clean XLSX format.',
    heroHeading: 'Commercial Bank of Dubai Statement to Excel Converter',
    heroSubheading: 'Convert your CBD PDF statements into clean Excel files. Extracts AED debit, credit, and balance columns with precision for CBD formats.',
    features: [
      'Handles CBD current account statements',
      'Extracts CBD AED interest and deposit columns',
      'Maps CBD running balance fields',
      'Supports CBD credit card statements',
    ],
    steps: [
      { title: 'Upload CBD PDF', description: 'Drag your Commercial Bank of Dubai statement PDF into the upload zone.' },
      { title: 'Column detection', description: 'The parser identifies CBD-specific columns like AED amounts and balances.' },
      { title: 'Download Excel', description: 'Get a formatted XLSX with all CBD transactions aligned.' },
    ],
    faqs: [
      { question: 'Does it work with CBD credit card statements?', answer: 'Yes, Commercial Bank of Dubai credit card PDF statements are supported.' },
      { question: 'Can I extract interest from CBD savings statements?', answer: 'Yes, interest columns from CBD savings accounts are extracted accurately.' },
    ],
    trustBadge: 'Optimized for CBD PDF formats',
  },
  {
    slug: 'union-national',
    name: 'Union National Bank (now Wio)',
    shortName: 'Union National',
    country: 'UAE',
    currency: 'AED',
    currencySymbol: 'AED',
    locale: 'en-AE',
    city: 'Abu Dhabi',
    tagline: 'Convert Union National Bank PDF statements to Excel',
    metaTitle: 'Union National Bank Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert Union National Bank statement PDFs to Excel. Extract AED transactions and balances into clean XLSX spreadsheet format.',
    heroHeading: 'Union National Bank Statement to Excel Converter',
    heroSubheading: 'Upload your Union National Bank PDF statement and receive a clean Excel file. Handles UNB account formats with precise column mapping.',
    features: [
      'Parses Union National Bank current account statements',
      'Extracts UNB AED withdrawal and deposit columns',
      'Maps UNB running balance fields',
      'Supports UNB savings account PDFs',
    ],
    steps: [
      { title: 'Upload UNB PDF', description: 'Drop your Union National Bank statement PDF into the upload area.' },
      { title: 'Structure detection', description: 'The parser identifies UNB column layouts automatically.' },
      { title: 'Export Excel', description: 'Download a clean Excel file with every UNB transaction mapped.' },
    ],
    faqs: [
      { question: 'Does it work with legacy UNB statements?', answer: 'Yes, Union National Bank PDF statements are supported including legacy formats.' },
      { question: 'Can I convert UNB AED amounts correctly?', answer: 'Yes, all AED transaction amounts are preserved with full decimal precision.' },
    ],
    trustBadge: 'Built for UNB formats',
  },
  {
    slug: 'nbq',
    name: 'National Bank of Umm Al Qaiwain (NBQ)',
    shortName: 'NBQ',
    country: 'UAE',
    currency: 'AED',
    currencySymbol: 'AED',
    locale: 'en-AE',
    city: 'Umm Al Quwain',
    tagline: 'Convert NBQ PDF statements to Excel',
    metaTitle: 'NBQ Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert National Bank of Umm Al Qaiwain statement PDFs to Excel. Extract AED transactions and balances into clean XLSX format.',
    heroHeading: 'NBQ Statement to Excel Converter',
    heroSubheading: 'Transform your NBQ PDF statements into organized Excel files. Handles National Bank of Umm Al Qaiwain account formats with precision.',
    features: [
      'Handles NBQ current and savings statements',
      'Extracts NBQ AED debit and credit columns',
      'Maps NBQ running balance fields',
      'Supports NBQ credit card PDFs',
    ],
    steps: [
      { title: 'Upload NBQ PDF', description: 'Add your NBQ statement PDF to the upload zone.' },
      { title: 'Format detection', description: 'The parser recognizes NBQ statement layouts automatically.' },
      { title: 'Download Excel', description: 'Get a clean XLSX with all NBQ transactions extracted.' },
    ],
    faqs: [
      { question: 'Does it work with NBQ savings statements?', answer: 'Yes, NBQ current and savings account PDF statements are both supported.' },
      { question: 'What NBQ statement types are supported?', answer: 'Checking, savings, and credit card NBQ PDF statements all work with the converter.' },
    ],
    trustBadge: 'Tailored for NBQ PDF layouts',
  },
  {
    slug: 'adib',
    name: 'Abu Dhabi Islamic Bank (ADIB)',
    shortName: 'ADIB',
    country: 'UAE',
    currency: 'AED',
    currencySymbol: 'AED',
    locale: 'en-AE',
    city: 'Abu Dhabi',
    tagline: 'Convert ADIB PDF statements to Excel',
    metaTitle: 'ADIB Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert Abu Dhabi Islamic Bank statement PDFs to Excel. Extract AED transactions, dates, and balances from ADIB statements.',
    heroHeading: 'ADIB Statement to Excel Converter',
    heroSubheading: 'Upload your Abu Dhabi Islamic Bank PDF statement and get a clean Excel file. Handles ADIB Sharia-compliant account formats with precision.',
    features: [
      'Parses ADIB current account statements',
      'Extracts ADIB AED transaction and balance columns',
      'Maps ADIB debit and credit columns',
      'Supports ADIB savings and credit card PDFs',
    ],
    steps: [
      { title: 'Upload ADIB PDF', description: 'Drop your Abu Dhabi Islamic Bank statement PDF into the upload zone.' },
      { title: 'Column detection', description: 'The parser identifies ADIB-specific columns including AED amounts and balances.' },
      { title: 'Export Excel', description: 'Download a formatted XLSX with all ADIB transactions aligned.' },
    ],
    faqs: [
      { question: 'Can I convert ADIB Sharia-compliant account statements?', answer: 'Yes, Abu Dhabi Islamic Bank Sharia-compliant account PDF statements are fully supported.' },
      { question: 'Does it work with ADIB Smart Banking statements?', answer: 'Yes, ADIB Smart Banking and online statement PDFs are both compatible.' },
    ],
    trustBadge: 'Optimized for ADIB formats',
  },
  {
    slug: 'unb-wio',
    name: 'Wio Bank PJSC',
    shortName: 'Wio',
    country: 'UAE',
    currency: 'AED',
    currencySymbol: 'AED',
    locale: 'en-AE',
    city: 'Abu Dhabi',
    tagline: 'Convert Wio Bank PDF statements to Excel',
    metaTitle: 'Wio Bank Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert Wio Bank statement PDFs to Excel online. Extract AED transactions, interest, and balances from Wio personal and business accounts.',
    heroHeading: 'Wio Bank Statement to Excel Converter',
    heroSubheading: 'Convert your Wio Bank PDF statements into clean Excel files. Handles Wio Personal and Wio Business account formats with precise column mapping.',
    features: [
      'Handles Wio Personal account statements',
      'Extracts Wio AED interest and transaction columns',
      'Maps Wio Business expense columns',
      'Supports Wio savings account PDFs',
    ],
    steps: [
      { title: 'Upload Wio PDF', description: 'Add your Wio Bank statement PDF to the upload zone.' },
      { title: 'Format detection', description: 'The parser recognizes Wio Bank digital-first statement layouts.' },
      { title: 'Download Excel', description: 'Get a clean XLSX with all Wio Bank transactions extracted.' },
    ],
    faqs: [
      { question: 'Does it work with Wio Personal and Wio Business?', answer: 'Yes, both Wio Personal and Wio Business account PDF statements are supported.' },
      { question: 'Can I extract Wio interest earned data?', answer: 'Yes, interest columns from Wio savings accounts are mapped accurately.' },
    ],
    trustBadge: 'Built for Wio Bank formats',
  },
  {
    slug: 'mashreq-neo',
    name: 'Mashreq Neo Bank',
    shortName: 'Mashreq Neo',
    country: 'UAE',
    currency: 'AED',
    currencySymbol: 'AED',
    locale: 'en-AE',
    city: 'Dubai',
    tagline: 'Convert Mashreq Neo PDF statements to Excel',
    metaTitle: 'Mashreq Neo Statement PDF to Excel Converter | ApexDoc',
    metaDescription: 'Convert Mashreq Neo digital bank statement PDFs to Excel. Extract AED transactions, transfers, and balances into clean XLSX format.',
    heroHeading: 'Mashreq Neo Statement to Excel Converter',
    heroSubheading: 'Upload your Mashreq Neo PDF statement and get a clean Excel file. Handles Mashreq Neo digital banking formats with precise column mapping.',
    features: [
      'Handles Mashreq Neo digital account statements',
      'Extracts Mashreq Neo AED transfer and payment columns',
      'Maps Mashreq Neo running balance fields',
      'Supports Mashreq Neo savings PDFs',
    ],
    steps: [
      { title: 'Upload Mashreq Neo PDF', description: 'Drop your Mashreq Neo statement PDF into the upload zone.' },
      { title: 'Format detection', description: 'The parser recognizes Mashreq Neo digital statement layouts.' },
      { title: 'Download Excel', description: 'Get a clean XLSX with all Mashreq Neo transactions extracted.' },
    ],
    faqs: [
      { question: 'Does it work with Mashreq Neo digital statements?', answer: 'Yes, Mashreq Neo digital banking PDF statements are fully supported.' },
      { question: 'Can I convert Mashreq Neo savings account statements?', answer: 'Yes, Mashreq Neo savings and current account PDFs both work with the converter.' },
    ],
    trustBadge: 'Tailored for Mashreq Neo PDF layouts',
  },
];

export function getBankBySlug(slug: string): BankInfo | undefined {
  return banks.find((b) => b.slug === slug);
}

export function getUsaBanks(): BankInfo[] {
  return banks.filter((b) => b.country === 'USA');
}

export function getUaeBanks(): BankInfo[] {
  return banks.filter((b) => b.country === 'UAE');
}
